apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: mysql  # Deployment повинен бути в тому ж namespace, що і база даних
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: ikulyk404/todoapp:3.0.0
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: app-secrets-volume
          mountPath: "/app/secrets"
          readOnly: true
        - name: app-config-volume
          mountPath: "/app/configs"
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        env:
        - name: DB_NAME  # Змінив назви змінних, щоб відповідати вимогам завдання
          valueFrom:
            secretKeyRef:
              name: app-secret  # App-secret, а не app-secrets
              key: NAME  # Ключ з secret
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: HOST
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PYTHONUNBUFFERED
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET_KEY
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql-data-mysql-0  # pvc для MYSQL, з іменем mysql-data-[statfulset-name]-[номер репліки]
      - name: app-secrets-volume
        secret:
          secretName: app-secret
      - name: app-config-volume
        configMap:
          name: app-config
