apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlzcWxyb290cGFzc3dvcmQ=
  MYSQL_USER: bXl1c2VyCg==
  MYSQL_PASSWORD: bXlwYXNzd29yZA==
