apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydatabase;
    USE mydatabase;
    CREATE TABLE IF NOT EXISTS tasks (
      id INT AUTO_INCREMENT PRIMARY KEY,
      description VARCHAR(255) NOT NULL
    );
    GRANT ALL PRIVILEGES ON mydatabase.* TO 'myuser'@'%' IDENTIFIED BY 'mypassword';
    FLUSH PRIVILEGES;
